#pragma once

#define NUMBER_OF_BACKGROUND_ELEMENTS 10
#define BACKGROUND_ELEMENT_SIZE 600
#define BACKGROUND_ELEMENT_SPEED 1

#define STAR_HEIGHT 125
#define STAR_WIDTH 50

#define PINK_STAR_TEXTURE_ID 1
#define PINK_STAR_MAX_NUMBER 7
#define PINK_STAR_POINT 5
#define PINK_STAR_MIN_SPEED 1
#define PINK_STAR_MAX_SPEED 3

#define GREEN_STAR_TEXTURE_ID 2
#define GREEN_STAR_MAX_NUMBER 5
#define GREEN_STAR_POINT 10
#define GREEN_STAR_MIN_SPEED 2
#define GREEN_STAR_MAX_SPEED 5

#define BLUE_STAR_TEXTURE_ID 3
#define BLUE_STAR_MAX_NUMBER 3
#define BLUE_STAR_POINT 15
#define BLUE_STAR_MIN_SPEED 3
#define BLUE_STAR_MAX_SPEED 7

#define GOLD_STAR_TEXTURE_ID 4
#define GOLD_STAR_MAX_NUMBER 2
#define GOLD_STAR_POINT 25
#define GOLD_STAR_MIN_SPEED 5
#define GOLD_STAR_MAX_SPEED 12

#define RED_STAR_TEXTURE_ID 5
#define RED_STAR_MAX_NUMBER 1
#define RED_STAR_POINT 50
#define RED_STAR_MIN_SPEED 7
#define RED_STAR_MAX_SPEED 22

#define MIN_SPEED_FOR_ASTEROIDS 1
#define MAX_SPEED_FOR_ASTEROIDS 6

#define SMALL_ASTEROID_HEIGHT 70
#define SMALL_ASTEROID_MAX_NUMBER 12
#define SMALL_ASTEROID_HEALTH 1
#define SMALL_ASTEROIDS_POINT 1

#define MEDIUM_ASTEROID_HEIGHT 120
#define MEDIUM_ASTEROID_MAX_NUMBER 7
#define MEDIUM_ASTEROID_HEALTH 3
#define MEDIUM_ASTEROIDS_POINT 3

#define LARGE_ASTEROID_HEIGHT 250
#define LARGE_ASTEROID_MAX_NUMBER 3
#define LARGE_ASTEROID_HEALTH 5
#define LARGE_ASTEROIDS_POINT 5

#define CRYSTAL_ASTEROID_HEIGHT 300
#define CRYSTAL_ASTEROID_MAX_NUMBER 5
#define CRYSTAL_ASTEROID_HEALTH 5
#define CRYSTAL_ASTEROID_POINT 10
#define MAX_SPEED_FOR_CRYSTAL_ASTEROIDS 2

#define ASTEROID_MIN_ROT 1
#define ASTEROID_MAX_ROT 7

#define CRYSTAL_ASTEROID_MAX_ROT 3

#define ASTEROID_Y_MULTIPLIER 3
#define CRYSTAL_ASTEROID_Y_MULTIPLIER 10
#define DEFAULT_Y_MULTIPLIER 5
